version: "3.3"
services:
    watchtower:
        container_name: watchtower
        restart: unless-stopped
        labels:
            - com.centurylinklabs.watchtower.enable=true
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: containrrr/watchtower
        command: '--label-enable --cleanup --interval 3600'
    
    warrior1:
        container_name: 'warrior1'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        environment:
            DOWNLOADER: St0ner1995
            SELECTED_PROJECT: auto
            CONCURRENT_ITEMS: 4
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8001:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
        
    warrior2:
        container_name: 'warrior2'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        environment:
            DOWNLOADER: St0ner1995
            SELECTED_PROJECT: auto
            CONCURRENT_ITEMS: 4
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8002:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
        
    warrior3:
        container_name: 'warrior3'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        environment:
            DOWNLOADER: St0ner1995
            SELECTED_PROJECT: auto
            CONCURRENT_ITEMS: 4
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8003:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
