version: "3.3"
services:
    watchtower:
        container_name: watchtower
        restart: unless-stopped
        labels:
            - com.centurylinklabs.watchtower.enable=true
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: containrrr/watchtower
        command: '--label-enable --cleanup --interval 3600'
    
    warrior1:
        container_name: 'warrior1'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        env_file: warrior.env
        environment:
            SELECTED_PROJECT: auto
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8001:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
        
    warrior2:
        container_name: 'warrior2'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        env_file: warrior.env
        environment:
            SELECTED_PROJECT: auto
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8002:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
        
    warrior3:
        container_name: 'warrior3'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        env_file: warrior.env
        environment:
            SELECTED_PROJECT: auto
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8003:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
        
    warrior4:
        container_name: 'warrior4'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        env_file: warrior.env
        environment:
            SELECTED_PROJECT: auto
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8004:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
    
    warrior5:
        container_name: 'warrior5'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        env_file: warrior.env
        environment:
            SELECTED_PROJECT: auto
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8005:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
    
    warrior6:
        container_name: 'warrior6'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        env_file: warrior.env
        environment:
            SELECTED_PROJECT: auto
        labels:
            - com.centurylinklabs.watchtower.enable=true
        ports:
            - '8006:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
