version: "3.3"
services:
    at-watchtower:
        container_name: at-watchtower
        restart: unless-stopped
        labels:
            - com.centurylinklabs.watchtower.enable=true
            - com.centurylinklabs.watchtower.scope=at-warrior
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: containrrr/watchtower
        command: '--label-enable --cleanup --interval 3600 --scope at-warrior'
    
    at-warrior1:
        container_name: 'at-warrior1'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        env_file: warrior.env
        environment:
            SELECTED_PROJECT: auto
        labels:
            - com.centurylinklabs.watchtower.enable=true
            - com.centurylinklabs.watchtower.scope=at-warrior
        ports:
            - '8001:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
        
    at-warrior2:
        container_name: 'at-warrior2'
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        env_file: warrior.env
        environment:
            SELECTED_PROJECT: auto
        labels:
            - com.centurylinklabs.watchtower.enable=true
            - com.centurylinklabs.watchtower.scope=at-warrior
        ports:
            - '8002:8001'
        image: atdr.meo.ws/archiveteam/warrior-dockerfile
